- name: Commit and Push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          # التحقق من وجود الملف قبل إضافته
          if [ -f "products_feed.xml" ]; then
            git add products_feed.xml
            git commit -m "Update products_feed.xml daily"
            git push
          else
            echo "File products_feed.xml not found, skipping commit."
          fi
